src/main/java/dto/NewsResult.java
package dto;

/**
 * @author yangxin
 * @time 2018/12/26  11:34
 */
public class NewsResult<T> {
    private boolean success;

    private T data;

    private String errMes;

    public NewsResult(boolean success, String errMes) {
        this.success = success;
        this.errMes = errMes;
    }

    public NewsResult(boolean success, T data) {
        this.success = success;
        this.data = data;
    }

    public void setSuccess(boolean success) {
        this.success = success;
    }

    public void setData(T data) {
        this.data = data;
    }

    public void setErrMes(String errMes) {
        this.errMes = errMes;
    }

    public boolean getIsSuccess() {
        return success;
    }

    public T getData() {
        return data;
    }

    public String getErrMes() {
        return errMes;
    }

    @Override
    public String toString() {
        return "NewsResult{" +
                "success=" + success +
                ", data=" + data +
                ", errMes='" + errMes + '\'' +
                '}';
    }
}

src/main/webapp/WEB-INF/jsp/AdminIndex.jsp
<%@ page import="entity.User" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@include file="common/tag.jsp" %>
<html>
<head>
    <title>后台主页-新闻列表</title>
    <%@include file="common/header.jsp" %>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/resource/css/to-do.css">
</head>
<body>


<section id="container">
    <!--header start-->
    <header class="header black-bg">
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
        </div>
        <!--logo start-->
        <a href="${pageContext.request.contextPath}/user/index.html" class="logo"><b><span>新闻页</span></b></a>
        <!--logo end-->
        <div class="top-menu">
            <ul class="pull-right top-menu">
                <br>
                <%
                    User user = (User) session.getAttribute("user");
                    if (user != null) {
                %>
                <li><a class="logout" href="${pageContext.request.contextPath}/user/Logout?userName=<%=user.getUserName()%>"
                >Logout</a></li>
                <%
                } else {
                %>
                <li><a class="logout" href="${pageContext.request.contextPath}/user/adminLogin.html">ToLogin</a></li>
                <%
                    }
                %>

            </ul>
        </div>
    </header>
    <!--header end-->
    <!--sidebar start-->

    <aside>
        <div id="sidebar" class="nav-collapse " tabindex="5000" style="overflow: hidden; outline: none;">
            <!-- sidebar menu start-->
            <ul class="sidebar-menu" id="nav-accordion">
                <p class="centered"><a href="">
                    <%
                        if (user != null) {/*说明已登录*/
                    %>
                    <img src="${pageContext.request.contextPath}/resource/img/ui-sam.jpg" class="img-circle" width="80">
                    <%
                    } else {
                    %>
                    <img src="" class="img-circle" width="80">
                    <%
                        }
                    %>

                </a>
                </p>
                <%

                    if (user != null) {/*说明已登录*/
                %>
                <h5 class="centered">管理员:<%=user.getUserName()%>
                </h5>
                <%
                } else {
                %>
                <h5 class="centered">请登录！！</h5>
                <%
                    }
                %>
                <li class="mt">
                    <a href="/new/adminIndex.html">
                        <i class="fa fa-dashboard"></i>
                        <span>首 页</span>
                    </a>
                </li>
                <li class="sub-menu dcjq-parent-li">
                    <a href="#" class="dcjq-parent">
                        <i class="fa fa-desktop"></i>
                        <span>文章列表</span>
                        <span class="dcjq-icon"></span></a>
                </li>
                <li class="sub-menu dcjq-parent-li">
                    <a href="${pageContext.request.contextPath}/new/commentlist.html" class="dcjq-parent">
                        <i class="fa fa-desktop"></i>
                        <span>评论列表</span>
                        <span class="dcjq-icon"></span></a>
                </li>
                <li class="sub-menu dcjq-parent-li">
                    <a href="${pageContext.request.contextPath}/new/userlist.html" class="dcjq-parent">
                        <i class="fa fa-desktop"></i>
                        <span>用户列表</span>
                        <span class="dcjq-icon"></span></a>
                </li>
                <li class="sub-menu dcjq-parent-li">
                    <a href="${pageContext.request.contextPath}/new/editor.html?index=2" class="dcjq-parent">
                        <i class="fa fa-desktop"></i>
                        <span>添加文章</span>
                        <span class="dcjq-icon"></span></a>
                </li>
            </ul>
            <!-- sidebar menu end-->
        </div>
    </aside>



    <!--sidebar end-->
    <!--main content start-->
    <section id="main-content">
        <div class="mt" style="margin-right: 5px;margin-left: 5px;margin-top: 5px;margin-bottom: 5px">

            <div class="col-md-12">
                <div style="color: rebeccapurple"></div>
                <div class="content-panel">
                    <h4><i class="fa fa-angle-right"></i> 新闻列表</h4>
                    <hr>
                    <div class="form-panel">
                        <form class="form-inline" role="form"
                              action="/new/seleceByLike" method="post"
                              style="display: contents">
                            <div class="form-group" style="display: contents">
                                <label class="sr-only" for="exampleInput1">模糊查询</label>
                                <span style="color: rebeccapurple" id="tip1"></span>
                                <input type="text" class="form-control" name="selectkey"  id="exampleInput1"
                                       placeholder="模糊查询">
                            </div>
                            <button type="submit" class="btn btn-theme">查找</button>
                        </form>
                        <form class="form-inline"
                              action="/new/seleceByKey"
                              style="display: contents">
                            <div class="form-group" style="display: contents">
                                <label class="sr-only" for="exampleInput2">关键字查询</label>
                                <span style="color: rebeccapurple" id="tip2"></span>
                                <input type="text" class="form-control" id="exampleInput2" name="selectkey"
                                       placeholder="关键字查询">
                            </div>
                            <button type="submit" class="btn btn-theme">查找</button>
                        </form>

                    </div>
                    <!-- /form-panel -->


                    <table class="table table-striped table-advance table-hover">
                        <thead>
                        <tr>
                            <th><i class="fa fa-bullhorn"></i> 编号</th>
                            <th><i class="fa fa-tags"></i> 类别</th>
                            <th><i class="fa fa-user"></i> 作者账户</th>
                            <th><i class="fa fa-tasks"></i> 标题</th>
                            <th class="hidden-phone"><i class="fa fa-question-circle"></i> 描述</th>
                            <th class="hidden-phone"><i class="fa fa-bars"></i> 发表时间</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        <c:forEach var="news" items="${Newslist}">
                            <tr>
                                <td>
                                        ${news.aNew.newId}
                                </td>
                                <td class="hidden-phone">${news.typeName}</td>
                                <td>${news.userName}</td>
                                <td>${news.aNew.title}</td>
                                <td id="desc">${news.aNew.keyWords}"</td>
                                <td><fmt:formatDate value="${news.aNew.createTime}"
                                                    pattern="yyyy-MM-dd HH:mm:ss"></fmt:formatDate></td>
                                <td>
                                    <a href="/new/detail?newId=${news.aNew.newId}">
                                        <button class="btn btn-success">
                                            <i class="fa fa-check">
                                                详情</i></button>
                                    </a>
                                    <a href="/new/edit?newId=${news.aNew.newId}&userName=${news.userName}">
                                        <button class="btn btn-primary"><i class="fa fa-pencil">修改
                                        </i></button>
                                    </a>
                                    <a href="/new/delete?newId=${news.aNew.newId}&userName=${news.userName}&tag=2">
                                        <button class="btn btn-danger">
                                            <i class="fa fa-trash-o ">
                                                删除</i></button>
                                    </a>

                                </td>
                            </tr>
                        </c:forEach>

                        </tbody>
                    </table>
                </div>
                <!-- /content-panel -->
            </div>
            <!-- /col-md-12 -->
        </div>
    </section>
    <!-- /MAIN CONTENT -->
    <!--main content end-->
    <!--footer start-->

    <%-- <%@include file="commentlist.jsp"%>--%>


    <footer class="site-footer">
        <div class="text-center">
            <p>
                © Copyrights <strong>杨鑫</strong>. All Rights Reserved
            </p>
            <div class="credits">
                Created with template by <a href="https://github.com/fireshoot/YxNews">Github</a>
            </div>
            <a href="adminIndex.html#" class="go-top">
                <i class="fa fa-angle-up"></i>
            </a>
        </div>
    </footer>
    <!--footer end-->
</section>

<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>
<script src="https://cdn.bootcss.com/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>

<script class="include" type="text/javascript"
        src="${pageContext.request.contextPath}/resource/lib/jquery.dcjqaccordion.2.7.js"></script>
<script src="https://cdn.bootcss.com/jquery-scrollTo/2.1.2/jquery.scrollTo.min.js"></script>
<script src="https://cdn.bootcss.com/jquery.nicescroll/3.7.6/jquery.nicescroll.js"></script>
<script src="${pageContext.request.contextPath}/resource/lib/common-scripts.js"></script>

<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<%--
<script type="text/javascript" src="${pageContext.request.contextPath}/resource/css/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/resource/css/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
--%>


<script src="${pageContext.request.contextPath}/resource/script/tasks.js" type="text/javascript"></script>
<script>
    jQuery(document).ready(function () {
        TaskList.initTaskWidget();
    });

    function checktext1() {
        text = document.getElementById("exampleInput1");
        tip = document.getElementById("tip1");
        if(text.value.toString()==""){
            tip.innerHTML="输入框不能为空";
            return false;
        }else{
            tip.innerHTML="";
            return true;
        }
    }
    function checktext2() {
        text = document.getElementById("exampleInput2");
        tip = document.getElementById("tip2");
        if(text.value.toString()==""){
            tip.innerHTML="输入框不能为空";
            return false;
        }else{
            tip.innerHTML="";
            return true;
        }
    }

    function detail(id) {
        location.href = "/new/delete?newId=" + id;
    }

    var desc = document.getElementById('desc').innerHTML;
    var text = desc.toString().substring(0, 20) + "......";
    var desc1 = document.getElementById('desc');

    desc1.innerHTML = text;


    /*
    * <p>你的事件应该绑定在按钮上，而不是ready上。<br/>var bready=false;<br/>B.addListener(&quot;ready&quot;,function(){bready=true;});//防止在按钮按下的时候，编辑器还没初始化<br/><br/>bt.addListener(&quot;click&quot;,function(){<br/>if (bready) B.setContent(&quot;内容&quot;);<br/>else B.addListener(&quot;ready&quot;,function(){B.setContent(&quot;内容&quot;);});//如果点下按钮时还没初始化，那么就等初始化完成的时候自动把内容放进去<br/>})<img src="/ueditor/jsp/upload/image/20181228/1545998530000092022.jpg" title="1545998530000092022.jpg" alt="机械师壁纸 (13).jpg"/></p>
    * */

    //wysihtml5 start

    /*    $('.wysihtml5').wysihtml5();*/

    //wysihtml5 end
    $(function () {
        $("#sortable").sortable();
        $("#sortable").disableSelection();
    });
</script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/AdminLogin.jsp
<%@ page import="org.springframework.ui.Model" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@include file="common/tag.jsp"%>
<html>
<head>
    <title>管理员登录</title>
    <%@include file="common/header.jsp"%>
</head>
<body>
<div id="login-page">
    <div class="container">
        <form class="form-login" action="${pageContext.request.contextPath}/user/toadminLogin" method="post">
            <h2 class="form-login-heading">管理员登录</h2>
            <div class="login-wrap">
                <input type="text" id="username" name="username" class="form-control" placeholder="User ID" autofocus>
                <br>
                <input type="password" id="password" name="password" class="form-control" placeholder="Password">
                <label class="checkbox">
                    <br>
                </label>
                <button class="btn btn-theme btn-block" id="submit" type="submit"><i class="fa fa-lock"></i>登 录</button>
                <div>
                    ${adminresult.errMes}
                    <%
                        session.removeAttribute("adminresult");
                    %>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>

<script src="https://cdn.bootcss.com/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>
<script src="${pageContext.request.contextPath}/resource/script/user.js" type="text/javascript"  charset="UTF-8"></script>

<script type="text/javascript">
    $.backstretch("${pageContext.request.contextPath}/resource/img/login-bg.jpg", {
        speed: 500
    });

    $(function(){
        user.Login.Submit();
    });
</script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/ForgetPassword.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@include file="common/tag.jsp"%>
<html>
<head>
    <title>忘记密码</title>
    <%@include file="common/header.jsp"%>
    <script type="text/javascript" src="${pageContext.request.contextPath}/resource/script/register.js"></script>
</head>
<body>
<div id="login-page">
    <div class="container">
        <form class="form-login"  onsubmit="return forgetcheckAll()"
              action="${pageContext.request.contextPath}/user/toforgetpassword" method="post">
            <h2 class="form-login-heading">找回密码</h2>
            <div class="login-wrap">
                <input type="text" id="username" onblur="checkname()" name="username" class="form-control" placeholder="User Name" autofocus>
                <span id="tip_name" style="color: rebeccapurple"></span>
                <br>
                <input type="text" id="email" name="email" onblur="checkemail()" class="form-control" placeholder="Email">
                <span id="tip_email" style="color: rebeccapurple"></span>
                <br>
                <input type="password" id="new_password" onblur="checkpsd1()" name="password" class="form-control" placeholder="New Password">
                <span id="tip_password" style="color: rebeccapurple"></span>
                    <span class="pull-right">
            <a data-toggle="modal" >通过验证邮箱重置密码</a>
            </span>
                </label>
                <button class="btn btn-theme btn-block" id="submit" type="submit"><i class="fa fa-lock"></i>找回密码</button>

                <div>
                    ${result.errMes}
                </div>
            </div>
        </form>
    </div>
</div>

<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>

<script src="https://cdn.bootcss.com/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>
<script src="${pageContext.request.contextPath}/resource/script/user.js" type="text/javascript"  charset="UTF-8"></script>

<script type="text/javascript">
    $.backstretch("${pageContext.request.contextPath}/resource/img/ny.jpg", {
        speed: 500
    });

    $(function(){
        user.Login.Submit();
    });
</script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/NewIndex.jsp
<%@ page import="entity.User" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<head>
    <title>主页</title>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <!-- Custom Theme files -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/css/bootstrap.css" rel="stylesheet">
    <link href="${pageContext.request.contextPath}/resource/css/style2.css" rel="stylesheet" type="text/css"
          media="all"/>
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <!--webfont-->
    <link href='http://fonts.useso.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic'
          rel='stylesheet' type='text/css'>
    <style>
        ul.top-menu > li > .logout {
            color: #f2f2f2;
            font-size: 12px;
            border-radius: 4px;
            -webkit-border-radius: 4px;
            border: 1px solid #64c3c2 !important;
            padding: 5px 15px;
            margin-right: 15px;
            background: #4ECDC4;
            margin-top: 15px;
        }
    </style>
</head>
<body>
<!-- header-section-starts -->
<div class="header">



    <div class="container">
        <div class="logo">
            <a href="index.html"><img src="${pageContext.request.contextPath}/resource/img/friends/fr-09.jpg"
                                      class="img-responsive" alt="" style="width: 100px; height: 100px"/></a>

            <label style="margin-left: 200px;font-size: 40px;margin: 0;color: #ffffff;">看神马新闻</label>
        </div>



        <div class="header-right">
            <%
                User user = (User) session.getAttribute("user");
                if (user != null) {
            %>
            <h4>欢迎用户<%=user.getUserName()%>
                <ul class="pull-right top-menu">
                    <li><a class="logout" href="${pageContext.request.contextPath}/user/Logout?userName=<%=user.getUserName()%>">Logout</a>
                    </li>
                </ul>
            </h4>
            <%
            } else {
            %>
            <h4>
                <div>未登录</div>
                <ul class="pull-right top-menu">
                    <li><a class="logout" href="${pageContext.request.contextPath}/user/login1.html">ToLogin</a></li>
                </ul>
            </h4>
            <%
                }
            %>

            <span class="menu"></span>
            <div class="top-menu">
                <ul>
                    <li><a class="active" href="#">新闻主页</a></li>
                    <li><a href="https://www.cnblogs.com/yangdagaoge/">项目日记</a></li>
                    <li><a href="https://github.com/fireshoot/YxNews">项目地址</a></li>
                    <li><a href="${pageContext.request.contextPath}/user/center.html">个人中心</a></li>
                </ul>
            </div>
            <!-- script for menu -->
            <script>
                $("span.menu").click(function () {
                    $(".top-menu").slideToggle("slow", function () {
                        // Animation complete.
                    });
                });
            </script>
            <!-- script for menu -->
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<c:if test="${!result.isSuccess}">
    <span style="color: rebeccapurple">${result.errMes}</span>
</c:if>
<!-- header-section-ends -->
<div class="content">
    <div class="blog-section">
        <div class="container">
            <div class="col-md-8 left_column" style="float: left">
                <h2 class="with-line">新闻列表</h2>
                <c:forEach var="data" items="${newData}">
                    <article class="clearfix">
                        <header class="grid_8 alpha">
                            <div class="sub">
                                <a href="/new/detail?newId=${data.aNew.newId}"
                                   class="readblog">${data.aNew.title}</a>
                                <p class="sub_head">Posted by <a href="#">${data.userName}</a> with <a href="#">3
                                    comment(s)</a>
                                </p>
                            </div>
                            <div class="clearfix"></div>
                        </header>
                        <c:if test="${data.aNew.newId%3==0}">
                            <div class="alpha1"><a href="/new/detail?newId=${data.aNew.newId}"><img
                                    src="${pageContext.request.contextPath}/resource/img/index-3_img-1.jpg" alt=""/></a>
                            </div>
                        </c:if>
                        <c:if test="${data.aNew.newId%3==1}">
                            <div class="alpha1"><a href="single.html"><img
                                    src="${pageContext.request.contextPath}/resource/img/index-3_img-2.jpg" alt=""/></a>
                            </div>
                        </c:if>
                        <c:if test="${data.aNew.newId%3==2}">
                            <div class="alpha1"><a href="single.html"><img
                                    src="${pageContext.request.contextPath}/resource/img/index-3_img-3.jpg" alt=""/></a>
                            </div>
                        </c:if>

                        <div class="grid_b4">
                            <h5>${data.aNew.title}</h5>
                            <p>${data.typeName}|${data.aNew.keyWords}</p>
                            <a href="/new/detail?newId=${data.aNew.newId}" class="btn btn-1 btn-1c">Read More</a>
                        </div>
                        <div class="clearfix"></div>
                    </article>
                </c:forEach>

            </div>

            <div class="col-md-4 right_column" style="float: left;">

                <div class="item2">
                    <header>
                        <h2 class="with-line">与我相关</h2>
                    </header>
                    <ul>
                        <li><a href="${pageContext.request.contextPath}/new/editor.html?index=1">添加文章</a></li>
                        <li><a href="${pageContext.request.contextPath}/user/center.html">我发表的文章</a></li>
                        <li><a href="${pageContext.request.contextPath}/user/center.html">我的评论</a></li>
                        <li><a href="${pageContext.request.contextPath}/user/center.html">我的消息</a></li>
                    </ul>
                </div>

                <div class="item">
                    <header>
                        <h2 class="with-line">新闻分类</h2>
                    </header>
                    <ul>
                        <li><a href="#">热点</a></li>
                        <li><a href="#">娱乐</a></li>
                        <li><a href="#">科技</a></li>
                        <li><a href="#">军事</a></li>
                        <li><a href="#">体育</a></li>
                        <li><a href="#">国际</a></li>
                    </ul>
                </div>

            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>


<div class="footer text-center">
    <div class="copyright">
        <p> © Copyrights <strong>杨鑫</strong>. All Rights Reserved
            <a target="_blank" href="https://github.com/fireshoot/YxNews">项目地址</a></p>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/jsp/editNews.jsp
<%@ page import="entity.User" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@include file="common/tag.jsp" %>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <title>文章编辑器</title>
    <style>
        .form-group {
            border: 1px solid #F2F3F6;
            display: inline-block;
            width: 80%;
            margin-bottom: 0;
        }
        .form-group label {
            line-height: 34px;
            width: 5%;
            float: left;
            padding-left: 5px;
            margin-bottom: 0;
        }
        .form-group input, .form-group input:focus {
            border: none;
            padding: 0;
            width: 80%;
            float: left;
            height: 6%;
        }
        h4 {
            font-size: 24px;
            color: #a2a2a2;
            font-weight: 300;
        }
        .btn-theme {
            color: #fff;
            background-color: #4ECDC4;
            border-color: #48bcb4;
        }
    </style>
</head>
<body>
<h4 style="margin-left: 100px;margin-top: 10px">${title}修改新闻</h4>

<div style="margin-left: 100px;margin-right: 100px;margin-top:50px;margin-bottom: 200px">
    <%
        User user=(User)session.getAttribute("user");
    %>

    <span>${updateResult.errMes}</span>

    <form action="${pageContext.request.contextPath}/new/update" method="post">

        <input style="display: none" name="newId" value="${editResult.data.aNew.newId}">

        <div class="form-group">
            <label for="to" class="">标 题:</label>
            <input type="text" name="title" tabindex="1" id="to" class="form-control" value="${editResult.data.aNew.title}">
        </div>
        <div class="form-group">
            <label for="category" class="">类 型:</label>
            <input type="text"  name="categoryId" tabindex="1" id="category" class="form-control"
                   value="${editResult.data.aNew.categoryId}">
            <span id="tip_category" style="color: rebeccapurple"></span>
        </div>
        <div class="form-group">
            <label for="dov" class="">作者:</label>
            <input type="text" name="author " tabindex="1" id="dov" class="form-control" value="${editResult.data.user.userName}">
        </div>
        <div class="form-group">
            <label for="do" class="">关键字:</label>
            <input type="text" name="keyWords" tabindex="1" id="do" class="form-control" value="${editResult.data.aNew.keyWords}">
        </div>
        <div id="NewContent" style="display: none">${editResult.data.aNew.content}</div>
        <!-- 加载编辑器的容器 -->
        <script id="container" name="content" type="text/plain">
        </script>

        <button class="btn-theme" id="submit" type="submit"><i class="fa fa-lock"></i>提 交</button>
    </form>
</div>

<!-- 配置文件 -->
<script type="text/javascript" src="${pageContext.request.contextPath}/resource/ueditor/ueditor.config.js" ></script>
<!-- 编辑器源码文件 -->
<script type="text/javascript" src="${pageContext.request.contextPath}/resource/ueditor/ueditor.all.js" ></script>
<!-- 实例化编辑器 -->
<script type="text/javascript">
    var ue = UE.getEditor('container');
    var tsg=document.getElementById('NewContent').innerHTML;
    setTimeout(function () {
        ue.setContent(tsg.toString());
    },500)


</script>


</body>
</html>

src/main/webapp/WEB-INF/jsp/login.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@include file="common/tag.jsp"%>
<html>
<head>
    <title>用户登录</title>
    <%@include file="common/header.jsp"%>
</head>
<body>
<div id="login-page">
    <div class="container">
        <form class="form-login" action="${pageContext.request.contextPath}/user/login" method="post">
            <h2 class="form-login-heading">用户登录</h2>
            <div class="login-wrap">
                <input type="text" id="username" name="username" class="form-control" placeholder="User ID" autofocus>
                <br>
                <input type="password" id="password" name="password" class="form-control" placeholder="Password">
                <label class="checkbox">
                    <input type="checkbox" value="remember-me"> Remember me
                    <span class="pull-right">
            <a data-toggle="modal" href="${pageContext.request.contextPath}/user/forgetpassword.html"> 忘记密码?</a>
            </span>
                </label>
                <button class="btn btn-theme btn-block" id="submit" type="submit"><i class="fa fa-lock"></i>登 录</button>
                <hr>
                <div style="color: rebeccapurple">
                        ${result.errMes}
                    <%
                        session.removeAttribute("result");
                    %>
                </div>
                <span id="killPhoneMessage" class="glyphicon"></span>
                <div class="registration">
                    还没有账户?<br/>
                    <a class="" href="${pageContext.request.contextPath}/user/register.html">
                        注册一个
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>

<script src="https://cdn.bootcss.com/jquery-backstretch/2.0.4/jquery.backstretch.min.js"></script>
<script src="${pageContext.request.contextPath}/resource/script/user.js" type="text/javascript"  charset="UTF-8"></script>

<script type="text/javascript">
    $.backstretch("${pageContext.request.contextPath}/resource/img/ny.jpg", {
        speed: 500
    });

    $(function(){
        user.Login.Submit();
    });
</script>

</body>
</html>